spring.application.name=NetPoint
spring.datasource.url=jdbc:postgresql://localhost:5432/net_point_spring
spring.datasource.username=postgres
spring.datasource.password=;xt(z+ZN!0G07l"0iG+MM2q4g
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver